version: "3.9"
services:
  chain-node:
    build: ../chain
    ports:
      - "8545:8545"
  backend:
    build: ../backend
    ports:
      - "4000:4000"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: obx
      POSTGRES_USER: obx
      POSTGRES_DB: obx
    ports:
      - "5432:5432"
